apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: debug-config
spec:
  args:
    - --debug
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-argocd-endpoint
spec:
  package: 'ghcr.io/krateoplatformops/provider-argocd-endpoint:VERSION'
  packagePullPolicy: IfNotPresent
  controllerConfigRef:
    name: debug-config